import React from 'react'
import { GetServerSideProps } from 'next'
import Head from 'next/head'

import { Sidebar } from '../../components/sidebar/Sidebar'
import ClientList from '../../components/clients/Clients'

import { Client } from '../../interfaces/Clients'

import { Box, CssBaseline, AppBar, Toolbar } from '@mui/material'
import { TypographyComponent } from '../../components/TypographyComponent'

// const baseUrl = process.env.API_URL

interface Props {
  clients: Client[]
}

const HomeClient = ({ clients }: Props) => {
  return (
    <div>
      <Head>
        <title>Controle Carros</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center' }}>
        <CssBaseline />
        <AppBar position='fixed' style={{ background: '#2E3B55' }} sx={{ zIndex: (theme) => theme.zIndex.drawer + 1 }} >
          <Toolbar className='toolbar'>
            <TypographyComponent />
          </Toolbar>
        </AppBar>
        <Sidebar />
        <ClientList clients={clients} />
      </Box>
    </div>
  )
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const res = await fetch('http://localhost:3000/api/clients')
  const clients = await res.json()
  return {
    props: { clients }
  }
}

export default HomeClient
