import React from 'react'

import Head from 'next/head'
import { Sidebar } from '../../components/sidebar/Sidebar'

import { Box, CssBaseline, AppBar, Toolbar } from '@mui/material'
import Clients from '../../components/clients/Clients'
import { TypographyComponent } from '../../components/TypographyComponent'

const Client: React.FC = () => {
  return (
    <div>
      <Head>
        <title>Controle Carros</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box sx={{ display: 'flex' }}>
        <CssBaseline />
        <AppBar position='fixed' style={{ background: '#2E3B55' }} sx={{ zIndex: (theme) => theme.zIndex.drawer + 1 }} >
          <Toolbar className='toolbar'>
            <TypographyComponent />
          </Toolbar>
        </AppBar>
        <Sidebar />
        <Clients />
      </Box>
    </div>
  )
}

export default Client
