import React from 'react'
import Head from 'next/head'

import { Sidebar } from '../../components/sidebar/Sidebar'
import New from '../../components/clients/New'

import { Box, CssBaseline, AppBar, Toolbar } from '@mui/material'
import { TypographyComponent } from '../../components/TypographyComponent'

const newClient: React.FC = () => {
  return (
    <div>
      <Head>
        <title>Controle Carros</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center' }}>
        <CssBaseline />
        <AppBar position='fixed' style={{ background: '#2E3B55' }} sx={{ zIndex: (theme) => theme.zIndex.drawer + 1 }} >
          <Toolbar className='toolbar'>
            <TypographyComponent />
          </Toolbar>
        </AppBar>
        <Sidebar />
        <New />
      </Box>
    </div>
  )
}

export default newClient
