import React from 'react'

import Head from 'next/head'
import { Sidebar } from '../components/sidebar/Sidebar'

const Home: React.FC = () => {
  return (
    <div>
      <Head>
        <title>Controle Carros</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Sidebar>
        <main>
          <h1>Controle Carros</h1>
        </main>
      </Sidebar>
    </div>
  )
}

export default Home
