import Head from 'next/head'
import Sidebar from '../components/Sidebar'

const Home: React.FC = () => {
  return (
    <div>
      <Head>
        <title>Controle Carros</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Sidebar />
    </div>
  )
}

export default Home
