import React from 'react'

import Head from 'next/head'
import { Sidebar } from '../components/sidebar/Sidebar'

import { Box, CssBaseline, AppBar, Toolbar, Typography } from '@mui/material'

const Home: React.FC = () => {
  return (
    <div>
      <Head>
        <title>Controle Carros</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box sx={{ display: 'flex' }}>
        <CssBaseline />
        <AppBar position='fixed' style={{ background: '#2E3B55' }} sx={{ zIndex: (theme) => theme.zIndex.drawer + 1 }} >
          <Toolbar style={{ justifyContent: 'space-between' }}>
            <Typography variant='h6' noWrap component='div' >
              Controle de Carros
            </Typography>
            <Typography variant='h6' noWrap component='div'>
              Usuário
            </Typography>
          </Toolbar>
        </AppBar>
        <Sidebar />
        <main>
          <h1>Carlos</h1>
        </main>
      </Box>
    </div>
  )
}

export default Home
